pipeline {
    agent any
    tools {
				gradle '7.5.0'
		}
    environment {
        imagename = "jojo0528/saproject"
        registryCredential = 'docker-hub'
        dockerImage = ''
    }

    stages {

        // gradle build
        stage('Bulid Gradle') {
          agent any
          steps {
            echo 'Bulid Gradle'
            dir ('.'){
                sh """
                ./gradlew clean build --exclude-task test
                """
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        // docker build
        stage('Bulid Docker') {
          agent any
          steps {
            echo 'Bulid Docker'
            script {
                  dockerImage = docker.build imagename
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        // docker push
        stage('Push Docker') {
          agent any
          steps {
            echo 'Push Docker'
            script {
                docker.withRegistry( '', registryCredential) {
                    dockerImage.push("${currentBuild.number}")  // ex) "1.0"
                }
            }
          }
          post {
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        stage('Deploy to dev') {
          steps {

              git credentialsId: 'github',
                      url: 'https://github.com/Jo-byung-geun/argocd.git',
                      branch: 'master'

              sh "sed -i 's/sa-project:.*\$/sa-project:${currentBuild.number}/g' sa-project/deployment.yaml"
              sh "git config user.name 'root'"
              sh "git config user.email 'jbg0528@naver.com'"
              sh "git add sa-project/deployment.yaml"
              sh "git commit -m '[UPDATE] sa-project ${currentBuild.number} image versioning'"

              withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'git-tool')]) {
                sh "git remote set-url origin https://github.com/Jo-byung-geun/argocd.git"
                sh "git push origin master"
              }
            }

           post {
                    failure {
                      echo 'Update fail'
                    }
                    success {
                      echo 'Update success'
                    }
            }
        }
    }
}